import { generateCustomer } from "../src/lib/synthetic";
import { extractSignals, networkFeatures } from "../src/lib/signals";
import { inferLifeEvent, timingCounterfactual } from "../src/lib/causal";
import { runSparsh, runPragati, runBandhan, runGyaan } from "../src/lib/agents";
const c = generateCustomer(42, { forceEvent: "WEDDING" });
const sig = extractSignals(c); const net = networkFeatures(c);
const inf = inferLifeEvent(sig); const t = timingCounterfactual(inf);
console.log("CUSTOMER:", c.name, c.age, c.city, c.language, "income", c.monthlyIncomeEstimate, "txns", c.txns.length, "existing", c.isExisting, "peakHour", c.peakAttentionHour);
console.log("SIGNALS:", Object.entries(sig).filter(([,v])=>v>0.05).map(([k,v])=>`${k}=${v}`).join(", "));
console.log("NET:", JSON.stringify(net));
console.log("POSTERIOR:", Object.entries(inf.posterior).filter(([,v])=>v>0.01).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${k}=${(v*100).toFixed(1)}%`).join(", "));
console.log("TOP:", inf.topEvent, "conf", inf.confidence, "daysToNeed", inf.daysToNeed);
console.log("DRIVERS:", inf.drivers.map(d=>`${d.signal}(${d.contribution})`).join(", "));
console.log("NEEDS:", inf.rankedNeeds.map(n=>`${n.need}=${n.score}`).join(", "));
console.log("TIMING: optimal", t.optimalDay, "actNow", t.actNowProb, "wait14", t.waitTwoWeeksProb, "uplift", t.upliftFromTiming);
const sp=runSparsh(c), pr=runPragati(c), ba=runBandhan(c), gy=runGyaan(c);
console.log("SPARSH:", sp.lifeEventScore, sp.financialHealthProxy, "trust", sp.trustRadius, sp.decision);
console.log("PRAGATI:", pr.comfort.score, pr.comfort.tier, "comps", pr.comfort.components.map(x=>x.value).join("/"));
console.log("BANDHAN:", ba.empathy.fei, ba.empathy.level, ba.response.mode);
console.log("GYAAN:", gy.cohortSize, gy.successRate, gy.topNextAction);
